### ISSUE TITLE
Get Gallery to an Accessibility Grade B

### ISSUE THREAD

**Issue by AgneLukoseviciute** [microsoft/react-native-gallery#295]
C = compliance/meets all Microsoft Accessibility Standards. B = user-friendly experience for all. 

The critical step here will be onboarding to have gallery tested through inclusive usability studies and acting on any feedback to ensure and confirm that gallery is "user friendly as defined by user feedback from people with disabilities confirming the product experience provides satisfaction, efficiency, and an intuitive experience."

Next steps are:
- [ ] #231 (Address outstanding a11y related issues)
- [ ] #293 (Address outstanding a11y related issues)
- [ ] #294 (Address outstanding a11y related issues)
- [ ] Get tested and confirm as resolved the leftover issues still open in ADO
- [ ] Onboard for usability studies and Grade B grading
- [ ] Address feedback from ^ (will open specific issues once we know what the work is)
