### ISSUE TITLE
Gallery on Fabric

### ISSUE THREAD

**Issue by Yajur-Grover** [microsoft/react-native-gallery#384]
This issue tracks the current progress towards publishing a fully-fleshed Fabric version of Gallery, providing all the features present on the current version of Gallery.

```[tasklist]
### Tasks
- [x] microsoft/react-native-gallery#387
- [x] microsoft/react-native-windows#12664
- [ ] On the Switch example page, the color does not change when closing a simple switch
- [ ] Padding between placeholder text and border of TextInput is much lower on the Fabric app compared to Paper
- [ ] Add a Hyperlink component as old RNX Hyperlink component no longer in use
- [ ] On the Image example page, some of the images appear to be slightly distorted compared to the current application
- [x] microsoft/react-native-gallery#386
- [x] microsoft/react-native-gallery#388
- [ ] microsoft/react-native-gallery#389
- [ ] No Settings page on Fabric app version
- [ ] microsoft/react-native-windows#12716
- [ ] microsoft/react-native-gallery#393
- [ ] microsoft/react-native-windows#12717
- [ ] microsoft/react-native-gallery#396
- [ ] microsoft/react-native-windows#12763 
- [ ] https://github.com/microsoft/react-native-gallery/issues/442
```

**Comment by chrisglein** [comment]
@Yajur-Grover Now that the Fabric gallery has been merged, how should we track/group the remaining issues here? It seems like bugs can be tracked as normal bugs (with the appropriate new arch label), the checkbox items might need to be upgraded to bugs, and then there's some standalone major tasks.

**Comment by Yajur-Grover** [comment]
Yes I think the remaining applicable sub-issues above can be broken up into individual issues, and this issue can be closed.
