### ISSUE TITLE
Rejuvenate visuals to match current WinUI gallery

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-gallery#405]
When React Native Gallery was created, it was before the WinUI gallery had experienced a significant visual rejuvenation. We should be able to show the same class of visuals with a bit of effort. Here are the high impact items I can identify.

### Splash image and set of useful links
![image](https://github.com/microsoft/react-native-gallery/assets/26607885/acfbc8ae-5bf4-4baa-8a51-9cf43b93e996)
Many of these are just as relevant within RN Gallery
- Getting started (can be link to https://aka.ms/reactnative or specifically the getting started subpage)
- Windows design
- Github
- Template Studio (are there still RNW templates in there?)
- Code samples (link to our samples repo)
- Partner Center

### Recently added/updated
![image](https://github.com/microsoft/react-native-gallery/assets/26607885/ebd28cd5-c2cc-4b71-ae73-782d7846440f)
![image](https://github.com/microsoft/react-native-gallery/assets/26607885/002ef55e-4209-4096-ae20-c445cb60e880)

### Design guidance
![image](https://github.com/microsoft/react-native-gallery/assets/26607885/e4c0a8d5-bb37-4d47-9014-52d682066d01)

### Control group subpages (with full color icons in page view)
![image](https://github.com/microsoft/react-native-gallery/assets/26607885/3cc20a86-e81b-4030-ab0a-f809a93b5ee9)
![image](https://github.com/microsoft/react-native-gallery/assets/26607885/3cf1fc23-4fb9-4149-9d96-c9eba541d595)

Contrast with RN Gallery which has groups only on the main page, and the icons are monochromatic:
![image](https://github.com/microsoft/react-native-gallery/assets/26607885/3e7a56a8-851b-41b8-a8a4-f834a3948513)

Work in progress snack to get started:
https://snack.expo.dev/4NjQuP5ias-bJa04RLYIk?platform=web
https://snack.expo.dev/wvKq-kD7PqlROjiiiswqx?platform=web

```[tasklist]
## Tasks
- [x] Add splash image to home page
- [x] Add list container for useful links
- [x] Add link to Getting started (https://aka.ms/reactnative)
- [x] Windows design (https://learn.microsoft.com/en-us/windows/apps/design/_)
- [x] Github (https://github.com/microsoft/react-native-windows/)
- [ ] Template Studio (https://marketplace.visualstudio.com/items?itemName=TemplateStudio.TemplateStudioForUWP)
- [x] Code samples (https://github.com/microsoft/react-native-windows-samples/)
- [x] Partner Center (https://developer.microsoft.com/en-us/windows/)
- [ ] https://github.com/microsoft/react-native-gallery/issues/433
- [ ] https://github.com/microsoft/react-native-gallery/issues/434
- [x] Replace monochromatic icons with full color icons (can take from https://github.com/microsoft/WinUI-Gallery/tree/main/WinUIGallery/Assets/ControlImages)
- [ ] https://github.com/microsoft/react-native-gallery/issues/435
- [x] Reshuffle groups to better align with WinUI gallery's grouping as appropriate (e.g. add Collections and move FlatList and friends into that)
- [ ] https://github.com/microsoft/react-native-gallery/issues/437
- [x] Code examples have a copy button
- [ ] https://github.com/microsoft/react-native-gallery/issues/216
- [x] Add indicator for new/updated samples
- [ ] https://github.com/microsoft/react-native-gallery/issues/436
- [x] Update readme image https://github.com/microsoft/react-native-gallery/blob/main/README.md
```

**Comment by chrisglein** [comment]
In checking dark mode with the rejuvenated home screen, I've also noticed some gaps in the existing code example implementation:

Before
![image](https://github.com/microsoft/react-native-gallery/assets/26607885/0ab11de8-7182-4c62-bd7b-eeee0df97f57)

After
![image](https://github.com/microsoft/react-native-gallery/assets/26607885/d9504702-5955-4705-83a4-ee58bb4f9832)

Note added copy buttons.

**Comment by chrisglein** [comment]
As long as we're adding clipboard as a dependency, we should have a clipboard example:

![image](https://github.com/microsoft/react-native-gallery/assets/26607885/9009d245-e715-4448-8c57-e6a3b41802d4)
Compare to WinUI gallery's similar clipboard sample:
![image](https://github.com/microsoft/react-native-gallery/assets/26607885/efbb7d59-3ffa-403b-b164-42e59e5f763b)

**Comment by chrisglein** [comment]
And since linear gradient was needed for the home page, can create a sample for it too:
![image](https://github.com/microsoft/react-native-gallery/assets/26607885/d2a05cc2-d20b-4f75-9811-0d4386dbb388)

**Comment by chrisglein** [comment]
With all the stuff merged so far:
![image](https://github.com/microsoft/react-native-gallery/assets/26607885/70c53550-12d3-43c4-ada6-fd0d26a52c8e)

**Comment by chrisglein** [comment]
Tracking remaining work with discrete issues (linked above). This issue itself can be considered complete (the visual updates are in the current store version on 0.74).
