### ISSUE TITLE
Copy to Clipboard has accessibility issues

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-gallery#418]
Was running some more FastPass checks and looks like there are a couple of accessibility issues with the 'copy to clipboard' icon as shown below: 
![image](https://github.com/microsoft/react-native-gallery/assets/157416350/7dae301e-f70d-474e-84b1-3d3242c2a348)

Doesn't look like a huge issue - main issue seems to be the Control Type and LocalizedControlType properties are set to Custom, and the Name property is not defined/has an invalid character. We can create a separate PR resolving this and merge it in.

_Originally posted by @Yajur-Grover in https://github.com/microsoft/react-native-gallery/issues/413#issuecomment-2071024692_
            
Contrast with WinUI 3 Gallery's accessibility tree:
![image](https://github.com/microsoft/react-native-gallery/assets/26607885/10dc9d96-d915-4c3b-9e6f-021bca001265)

```[tasklist]
### Tasks
- [x] Focusable sibling elements must not have the same Name and LocalizedControlType
- [x] The ControlType and LocalizedControlType must not both be set to "custom."
- [x] The Name property must not contain any characters in the private Unicode range.
```

**Comment by chrisglein** [comment]
With proposed fix:
![image](https://github.com/microsoft/react-native-gallery/assets/26607885/46ada7ab-57dd-4a45-8c8a-d485ed26c79a)
