### ISSUE TITLE
Hamburger menu button has odd accessibility labeling

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-gallery#429]
Something doesn't feel right about how the drawer hamburger menu is showing to accessibility:

Collapsed:
![image](https://github.com/microsoft/react-native-gallery/assets/26607885/7288fdc6-d105-4d58-9126-08de9cf34698)
Expanded:
![image](https://github.com/microsoft/react-native-gallery/assets/26607885/4ee1bf80-a78f-412f-b77d-708a0a9292b0)

Contrast with WinUI 3 Gallery's button:
Collapsed:
![image](https://github.com/microsoft/react-native-gallery/assets/26607885/ceed9d9b-7ae9-4add-b5a6-7eebe3a4f662)
Expanded:
![image](https://github.com/microsoft/react-native-gallery/assets/26607885/3fc62123-eb3b-44d7-9dd4-1770513da21b)

```[tasklist]
### Tasks
- [ ] Uses `TouchableHighlight` instead of `Pressable`
- [ ] Has different labels depending on press state
- [ ] Has child text item that shows not-legible text to accessibility
- [ ] Update terms to match ("Navigation" instead of "drawer")
- [ ] #407 
```

**Comment by chrisglein** [comment]
Something to investigate: Should this use WinUI's standardized menu button for this so we get alignment for free? Can that be extracted from navigation view like the back button can, or is it baked in and we just need to align?
